// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Device.proto

package Device

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Command_DeviceType int32

const (
	Command_TV        Command_DeviceType = 0
	Command_SOUND_BAR Command_DeviceType = 1
)

var Command_DeviceType_name = map[int32]string{
	0: "TV",
	1: "SOUND_BAR",
}

var Command_DeviceType_value = map[string]int32{
	"TV":        0,
	"SOUND_BAR": 1,
}

func (x Command_DeviceType) String() string {
	return proto.EnumName(Command_DeviceType_name, int32(x))
}

func (Command_DeviceType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f4afdabe20ec8a36, []int{0, 0}
}

type Command_Action int32

const (
	Command_TURN_OFF Command_Action = 0
	Command_TURN_ON  Command_Action = 1
)

var Command_Action_name = map[int32]string{
	0: "TURN_OFF",
	1: "TURN_ON",
}

var Command_Action_value = map[string]int32{
	"TURN_OFF": 0,
	"TURN_ON":  1,
}

func (x Command_Action) String() string {
	return proto.EnumName(Command_Action_name, int32(x))
}

func (Command_Action) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f4afdabe20ec8a36, []int{0, 1}
}

type Command struct {
	Device               Command_DeviceType `protobuf:"varint,1,opt,name=device,proto3,enum=Device.Command_DeviceType" json:"device,omitempty"`
	Action               Command_Action     `protobuf:"varint,2,opt,name=action,proto3,enum=Device.Command_Action" json:"action,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Command) Reset()         { *m = Command{} }
func (m *Command) String() string { return proto.CompactTextString(m) }
func (*Command) ProtoMessage()    {}
func (*Command) Descriptor() ([]byte, []int) {
	return fileDescriptor_f4afdabe20ec8a36, []int{0}
}

func (m *Command) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Command.Unmarshal(m, b)
}
func (m *Command) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Command.Marshal(b, m, deterministic)
}
func (m *Command) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Command.Merge(m, src)
}
func (m *Command) XXX_Size() int {
	return xxx_messageInfo_Command.Size(m)
}
func (m *Command) XXX_DiscardUnknown() {
	xxx_messageInfo_Command.DiscardUnknown(m)
}

var xxx_messageInfo_Command proto.InternalMessageInfo

func (m *Command) GetDevice() Command_DeviceType {
	if m != nil {
		return m.Device
	}
	return Command_TV
}

func (m *Command) GetAction() Command_Action {
	if m != nil {
		return m.Action
	}
	return Command_TURN_OFF
}

func init() {
	proto.RegisterEnum("Device.Command_DeviceType", Command_DeviceType_name, Command_DeviceType_value)
	proto.RegisterEnum("Device.Command_Action", Command_Action_name, Command_Action_value)
	proto.RegisterType((*Command)(nil), "Device.Command")
}

func init() { proto.RegisterFile("Device.proto", fileDescriptor_f4afdabe20ec8a36) }

var fileDescriptor_f4afdabe20ec8a36 = []byte{
	// 169 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x71, 0x49, 0x2d, 0xcb,
	0x4c, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x83, 0xf0, 0x94, 0xb6, 0x33, 0x72,
	0xb1, 0x3b, 0xe7, 0xe7, 0xe6, 0x26, 0xe6, 0xa5, 0x08, 0x19, 0x71, 0xb1, 0xa5, 0x80, 0x45, 0x25,
	0x18, 0x15, 0x18, 0x35, 0xf8, 0x8c, 0xa4, 0xf4, 0xa0, 0x5a, 0xa0, 0x0a, 0xa0, 0xdc, 0x90, 0xca,
	0x82, 0xd4, 0x20, 0xa8, 0x4a, 0x21, 0x3d, 0x2e, 0xb6, 0xc4, 0xe4, 0x92, 0xcc, 0xfc, 0x3c, 0x09,
	0x26, 0xb0, 0x1e, 0x31, 0x74, 0x3d, 0x8e, 0x60, 0xd9, 0x20, 0xa8, 0x2a, 0x25, 0x65, 0x2e, 0x2e,
	0x84, 0x29, 0x42, 0x6c, 0x5c, 0x4c, 0x21, 0x61, 0x02, 0x0c, 0x42, 0xbc, 0x5c, 0x9c, 0xc1, 0xfe,
	0xa1, 0x7e, 0x2e, 0xf1, 0x4e, 0x8e, 0x41, 0x02, 0x8c, 0x4a, 0xca, 0x5c, 0x6c, 0x10, 0x6d, 0x42,
	0x3c, 0x5c, 0x1c, 0x21, 0xa1, 0x41, 0x7e, 0xf1, 0xfe, 0x6e, 0x6e, 0x02, 0x0c, 0x42, 0xdc, 0x5c,
	0xec, 0x10, 0x9e, 0x9f, 0x00, 0x63, 0x12, 0x1b, 0xd8, 0x23, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x09, 0x9a, 0x24, 0xdd, 0xd8, 0x00, 0x00, 0x00,
}
