/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.3 at Sat Mar 30 18:56:46 2019. */

#include "Device.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t Device_Command_fields[3] = {
    PB_FIELD(  1, UENUM   , SINGULAR, STATIC  , FIRST, Device_Command, device, device, 0),
    PB_FIELD(  2, UENUM   , SINGULAR, STATIC  , OTHER, Device_Command, action, device, 0),
    PB_LAST_FIELD
};




/* @@protoc_insertion_point(eof) */
